#!/usr/bin/env bash
# This prints a bash script loop from 1 to 10
#displaying bad luck for the 4th loop, good luck
#for the 8th loop and best school for the other loops
var=0
while [ "$var" -ne 10 ];
do
    if [ "$var" -eq 3 ]; then
        echo bad luck
    elif [ "$var" -eq 7 ]; then
        echo good luck
    else
        echo Best School
    fi
    ((var++))
    done 
